// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingConfirmController from "./booking_confirm_controller"
application.register("booking-confirm", BookingConfirmController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import MapController from "./map_controller"
application.register("map", MapController)


import ReviewController from "./review_controller"
application.register("review", ReviewController)

import SearchFieldRevealController from "./search_field_reveal_controller"
application.register("search-field-reveal", SearchFieldRevealController)
